In [28]:
import pandas as pd
a=[[1,'Sachin Tendulkar'],[2,'MS Dhoni'],[3,'Virat Kohli']]
df=pd.DataFrame(a,columns=['SNo','Name'])
df

   SNo              Name
0    1  Sachin Tendulkar
1    2          MS Dhoni
2    3       Virat Kohli

In [29]:
df=df.assign(First_Name=lambda x:x['Name'].str.split(' ').str[0])
df

   SNo              Name First_Name
0    1  Sachin Tendulkar     Sachin
1    2          MS Dhoni         MS
2    3       Virat Kohli      Virat

In [30]:
mappings={1:'Batsman',2:'WicketKeeper',3:'Batsman'}
df['skill']=df['SNo'].map(mappings)
df

   SNo              Name First_Name         skill
0    1  Sachin Tendulkar     Sachin       Batsman
1    2          MS Dhoni         MS  WicketKeeper
2    3       Virat Kohli      Virat       Batsman

In [31]:
df2=pd.DataFrame(a,columns=['SNo','Name'])
df2

   SNo              Name
0    1  Sachin Tendulkar
1    2          MS Dhoni
2    3       Virat Kohli

In [32]:
b=[[4,'Jadeja'],[5,'Bumrah']]
df3=pd.DataFrame(b,columns=['SNo','Name'])
df3

   SNo    Name
0    4  Jadeja
1    5  Bumrah

In [39]:
df5=pd.concat([df2,df3],axis=0)
df5.reset_index(drop=True)

   SNo              Name
0    1  Sachin Tendulkar
1    2          MS Dhoni
2    3       Virat Kohli
3    4            Jadeja
4    5            Bumrah

In [40]:
c=[[1,'MI'],[2,'CSK'],[3,'RCB']]
df6=pd.DataFrame(c,columns=['SNo','Team'])
df6

   SNo Team
0    1   MI
1    2  CSK
2    3  RCB

In [46]:
df7=pd.merge(df2,df6,on='SNo',how='left')
df7

   SNo              Name Team
0    1  Sachin Tendulkar   MI
1    2          MS Dhoni  CSK
2    3       Virat Kohli  RCB